# Generated by Django 4.2 on 2023-04-17 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Analogs', '0003_alter_analogs_options_alter_products_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='_analogs',
            new_name='analogs',
        ),
    ]
