# Generated by Django 4.2 on 2023-04-17 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analogs', '0004_rename__analogs_products_analogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='analogs',
            name='new_id',
            field=models.CharField(default='new', max_length=33),
        ),
    ]
