# Generated by Django 4.2 on 2023-04-17 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Analogs', '0005_analogs_new_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analogs',
            name='new_id',
        ),
    ]
