# Generated by Django 4.2 on 2023-04-17 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Analogs', '0006_remove_analogs_new_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='analogs',
            new_name='_analogs',
        ),
    ]
