# Generated by Django 4.2 on 2023-04-18 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analogs', '0007_rename_analogs_products__analogs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('products', models.ManyToManyField(to='Analogs.products')),
            ],
        ),
    ]
